### ISSUE TITLE
RUN ERROR: mfa: command not found

### ISSUE THREAD

**Issue by blldd** [chenht2010/Voicebox#1]
Hi Haitao, Thanks for your great work, I am trying to run it on my machine, but unfortunately, encountered an error when I run prepare.sh:  

line 47: mfa: command not found

Do you have any idea how to fix this? Thanks!

**Comment by chenht2010** [comment]
Sorry for unclear instruction. If you want use MFA, you need install "montreal-forced-aligner". 

I suggest creating a conda env:

conda create -n aligner -c conda-forge montreal-forced-aligner -y
conda activate aligner
bash prepare.sh
conda deactivate

**Comment by blldd** [comment]
> 
I followed your advice to install by conda, and make sure to install english_us_mfa, but when I run prepare.sh, it always error when 9,755 , and do you have any idea about this?


```

 ~/repo/Voicebox/examples/ljspeech$ bash prepare.sh 
Step 3: MFA, if error, pls check ./temp dir

 INFO     Setting up corpus information...                                                                                                   
 INFO     Loading corpus from source files...                                                                                                
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12,708/100  [ 0:00:00 < 0:00:00 , 4,049 it/s ]
 INFO     Found 1 speaker across 13100 files, average number of utterances per speaker: 13100.0                                              
 INFO     Initializing multiprocessing jobs...                                                                                               
 WARNING  Number of jobs was specified as 4, but due to only having 1 speakers, MFA will only use 1 jobs. Use the --single_speaker flag if   
          you would like to split utterances across jobs regardless of their speaker.                                                        
 INFO     Normalizing text...                                                                                                                
  94% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 12,299/13,100  [ 0:00:04 < 0:00:01 , 7,673 it/s ]
 INFO     Generating MFCCs...                                                                                                                
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 13,099/13,100  [ 0:04:31 < 0:00:01 , 49 it/s ]
 INFO     Calculating CMVN...                                                                                                                
 INFO     Generating final features...                                                                                                       
  99% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 12,954/13,100  [ 0:00:05 < 0:00:01 , 2,717 it/s ]
 INFO     Creating corpus split...                                                                                                           
  74% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 9,755/13,100  [ 0:00:01 < 0:00:01 , 94,694 it/s ]
 ERROR    There was an error in the run, please see the log.                                                                                 
Exception ignored in atexit callback: <bound method ExitHooks.history_save_handler of <montreal_forced_aligner.command_line.mfa.ExitHooks object at 0x7fb1a762aed0>>
Traceback (most recent call last):
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/montreal_forced_aligner/command_line/mfa.py", line 99, in history_save_handler
    raise self.exception
  File "/data0/zongboyu/anaconda3/envs/mfa/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
             ^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/montreal_forced_aligner/command_line/align.py", line 111, in align_corpus_cli
    aligner.align()
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 451, in align
    super().align()
  File "/data0/zongboyu/anaconda3/envs/mfa/lib/python3.11/site-packages/montreal_forced_aligner/alignment/base.py", line 352, in align
    assert self.alignment_model_path.suffix == ".alimdl"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 
```

**Comment by chenht2010** [comment]
You are using v3.0.0?  Use an older version like 2.2.17 or 2.2.15. I think the latest version v3.0.0 alpha may have some bugs, or maybe its API changes.

I'll update the instructions.

**Comment by chenht2010** [comment]
You are using v3.0.0?  Use an older version like 2.2.17 or 2.2.15. I think the latest version v3.0.0 alpha may have some bugs, or maybe its API changes.

I'll update the instructions.

**Comment by blldd** [comment]
I am using Montreal-Forced-Aligner==3.0.0a4, Thank you for your suggestion, and I will try later with v2.2.*
